/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JOptionPane;

public class AdministratorGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdministratorGUI
     */
    public AdministratorGUI() {
        initComponents();
        setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ViewDoctors = new javax.swing.JButton();
        ViewPatients = new javax.swing.JButton();
        ProcessBills = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        GenerateBill = new javax.swing.JButton();
        ProcessPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ViewDoctors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewDoctors.setText("View Doctors");
        ViewDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDoctorsActionPerformed(evt);
            }
        });
        getContentPane().add(ViewDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        ViewPatients.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ViewPatients.setText("View Patients");
        ViewPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPatientsActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        ProcessBills.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProcessBills.setText("Process Bills");
        ProcessBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessBillsActionPerformed(evt);
            }
        });
        getContentPane().add(ProcessBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        GenerateBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenerateBill.setText("Generate Bill");
        GenerateBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateBillActionPerformed(evt);
            }
        });
        getContentPane().add(GenerateBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        ProcessPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProcessPayment.setText("Process Payment");
        ProcessPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessPaymentActionPerformed(evt);
            }
        });
        getContentPane().add(ProcessPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel1.setText("Administrator Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/b.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-340, -20, 1130, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPatientsActionPerformed
        // TODO add your handling code here:
            showFileData("Patients.txt", "Patients List");

        
    }//GEN-LAST:event_ViewPatientsActionPerformed

    private void ProcessPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessPaymentActionPerformed
        // TODO add your handling code here:
            new BillGUI().setVisible(true);

    }//GEN-LAST:event_ProcessPaymentActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
            new MainMenuGUI().setVisible(true);
    dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void ViewDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDoctorsActionPerformed
        // TODO add your handling code here:
         showFileData("Doctors.txt", "Doctors List");
    }//GEN-LAST:event_ViewDoctorsActionPerformed

    private void GenerateBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateBillActionPerformed
        // TODO add your handling code here:
            new BillGUI().setVisible(true);

    }//GEN-LAST:event_GenerateBillActionPerformed

    private void ProcessBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessBillsActionPerformed
        // TODO add your handling code here:
            new BillGUI().setVisible(true);

    }//GEN-LAST:event_ProcessBillsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorGUI().setVisible(true);
            }
        });
    }
    private void showFileData(String fileName, String title) {
    try {
        BufferedReader br = new BufferedReader(new FileReader(fileName));
        StringBuilder data = new StringBuilder();
        String line;

        while ((line = br.readLine()) != null) {
            data.append(line).append("\n");
        }
        br.close();

        if (data.length() == 0) {
            JOptionPane.showMessageDialog(this, "No records found.");
        } else {
            JOptionPane.showMessageDialog(this, data.toString(), title, JOptionPane.INFORMATION_MESSAGE);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "File not found: " + fileName);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton GenerateBill;
    private javax.swing.JButton ProcessBills;
    private javax.swing.JButton ProcessPayment;
    private javax.swing.JButton ViewDoctors;
    private javax.swing.JButton ViewPatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
