/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author bagya
 */
public class AppointmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentGUI
     */
    public AppointmentGUI() {
        initComponents();
          setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null); // center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AppointmentID = new javax.swing.JLabel();
        PatientID = new javax.swing.JLabel();
        DoctorID = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Notes = new javax.swing.JLabel();
        Status = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        Schedule = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        MAINMENU = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Appointment Management");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Appointment ");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 10, 150, -1));

        AppointmentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AppointmentID.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentID.setText("Appointment ID");
        getContentPane().add(AppointmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        PatientID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PatientID.setForeground(new java.awt.Color(255, 255, 255));
        PatientID.setText("Patient ID");
        getContentPane().add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 85, 30));

        DoctorID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DoctorID.setForeground(new java.awt.Color(255, 255, 255));
        DoctorID.setText("Doctor ID");
        getContentPane().add(DoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 85, 20));

        Date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 255, 255));
        Date.setText("Date");
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 85, -1));

        Time.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Time");
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 85, -1));

        Type.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setText("Type");
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 85, 30));

        Notes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Notes.setForeground(new java.awt.Color(255, 255, 255));
        Notes.setText("Notes");
        getContentPane().add(Notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 85, -1));

        Status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Status.setForeground(new java.awt.Color(255, 255, 255));
        Status.setText("Status");
        getContentPane().add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 85, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 99, 25));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 99, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 99, 25));

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 99, 25));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 99, 25));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 99, 25));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 99, 25));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select status", "Scheduled", "Cancelled", "Completed" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, 25));

        Schedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Schedule.setText("Schedule");
        Schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleActionPerformed(evt);
            }
        });
        getContentPane().add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, -1));

        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        MAINMENU.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MAINMENU.setText("MAIN MENU");
        MAINMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAINMENUActionPerformed(evt);
            }
        });
        getContentPane().add(MAINMENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 45, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 567, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/7.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, 0, 920, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void ScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleActionPerformed
        // TODO add your handling code here:
              if (jTextField1.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter Appointment ID");
    return;
}
              
        Appointment appointment = new Appointment();
        appointment.setAppointmentID(jTextField1.getText());
        appointment.setPatient(jTextField2.getText());
        appointment.setDoctor(jTextField3.getText());
        appointment.setAppointmentDate(jTextField4.getText());
        appointment.setAppointmentTime(jTextField5.getText());
        appointment.setType(jTextField6.getText());
        appointment.setNotes(jTextField7.getText());
        appointment.setStatus(jComboBox1.getSelectedItem().toString());
        appointment.scheduleAppointment();
    javax.swing.JOptionPane.showMessageDialog(this, "Appointment scheduled successfully");
    clearFields();

try {
    File file = new File("Appointment.txt");
    FileWriter writer = new FileWriter(file, true);

    String format = "%-12s %-12s %-12s %-15s %-10s %-12s %-15s %-12s\n";

    if (file.length() == 0) {
        String header = String.format(format,
            "AppointmentID",
            "PatientID",
            "DoctorID",
            "Date",
            "Time",
            "Type",
            "Notes",
            "Status"
        );
        writer.write(header);
    }

    String line = String.format(format,
        jTextField1.getText(),
        jTextField2.getText(),
        jTextField3.getText(),
        jTextField4.getText(),
        jTextField5.getText(),
        jTextField6.getText(),
        jTextField7.getText(),
        jComboBox1.getSelectedItem().toString()
    );

    writer.write(line);
    writer.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "File error", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_ScheduleActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed

        if (jTextField1.getText().trim().isEmpty()) {
          JOptionPane.showMessageDialog(this, "Please enter Appointment ID");
        return;
        }
        
    String targetID = jTextField1.getText();
    ArrayList<String> lines = new ArrayList<>();

    try {
        BufferedReader reader = new BufferedReader(new FileReader("Appointment.txt"));
        String line;

        while ((line = reader.readLine()) != null) {
            if (line.startsWith("AppointmentID")) {
                lines.add(line);
                continue;
            }

            if (line.trim().startsWith(targetID)) {
                String format = "%-12s %-12s %-12s %-15s %-10s %-12s %-15s %-12s";
                String updatedLine = String.format(format,
                        jTextField1.getText(),
                        jTextField2.getText(),
                        jTextField3.getText(),
                        jTextField4.getText(),
                        jTextField5.getText(),
                        jTextField6.getText(),
                        jTextField7.getText(),
                        jComboBox1.getSelectedItem().toString()
                );
                lines.add(updatedLine);
            } else {
                lines.add(line);
            }
        }

        reader.close();

        FileWriter writer = new FileWriter("Appointment.txt", false);
        for (String l : lines) {
            writer.write(l + "\n");
        }
        writer.close();

        JOptionPane.showMessageDialog(this, "Appointment updated successfully");
       clearFields();

    } 
    
    catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Update failed", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_UpdateActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed

        if (jTextField1.getText().trim().isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please enter Appointment ID");
    return;
}
    String targetID = jTextField1.getText();
    ArrayList<String> lines = new ArrayList<>();

    try {
        BufferedReader reader = new BufferedReader(new FileReader("Appointment.txt"));
        String line;

        while ((line = reader.readLine()) != null) {
            if (line.startsWith("AppointmentID")) {
                lines.add(line);
                continue;
            }

            if (!line.trim().startsWith(targetID)) {
                lines.add(line);
            }
        }

        reader.close();

        FileWriter writer = new FileWriter("Appointment.txt", false);
        for (String l : lines) {
            writer.write(l + "\n");
        }
        writer.close();
   
        JOptionPane.showMessageDialog(this, "Appointment cancelled and removed");
clearFields();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Cancel failed", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_CancelActionPerformed

    private void MAINMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAINMENUActionPerformed
        // TODO add your handling code here:
        new MainMenuGUI().setVisible(true);
this.dispose();

    }//GEN-LAST:event_MAINMENUActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentGUI().setVisible(true);
            }
        });
    }
private void clearFields() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jComboBox1.setSelectedIndex(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppointmentID;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel DoctorID;
    private javax.swing.JButton MAINMENU;
    private javax.swing.JLabel Notes;
    private javax.swing.JLabel PatientID;
    private javax.swing.JButton Schedule;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Type;
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
