/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

/**
 *
 * @author bagya
 */
public class MainMenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MAINclass
     */
    public MainMenuGUI() {
        initComponents(); 
        setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null); // center screen
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainMenu = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();
        Appointment = new javax.swing.JButton();
        PatientRegistration = new javax.swing.JButton();
        medistaff = new javax.swing.JButton();
        staff = new javax.swing.JButton();
        Administrator = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenu.setFont(new java.awt.Font("Sitka Banner", 1, 24)); // NOI18N
        MainMenu.setText("Main Menu");
        getContentPane().add(MainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        Logout.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        Appointment.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        Appointment.setText("Appointment");
        Appointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(Appointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        PatientRegistration.setFont(new java.awt.Font("Sitka Small", 1, 12)); // NOI18N
        PatientRegistration.setText("Patient Registration");
        PatientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientRegistrationActionPerformed(evt);
            }
        });
        getContentPane().add(PatientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        medistaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medistaff.setText("Medical Staff");
        medistaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medistaffActionPerformed(evt);
            }
        });
        getContentPane().add(medistaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        staff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staff.setText("Staff");
        staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffActionPerformed(evt);
            }
        });
        getContentPane().add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, -1, -1));

        Administrator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Administrator.setText("Administrator");
        Administrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministratorActionPerformed(evt);
            }
        });
        getContentPane().add(Administrator, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/b.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientRegistrationActionPerformed
        // TODO add your handling code here:
         new PatientRegistation().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PatientRegistrationActionPerformed

    private void AppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentActionPerformed
        // TODO add your handling code here:
        new AppointmentGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AppointmentActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        new LOGIN().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void medistaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medistaffActionPerformed
        // TODO add your handling code here:

    new MedicalstaffGUI().setVisible(true);
    this.dispose(); 

    }//GEN-LAST:event_medistaffActionPerformed

    private void staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffActionPerformed
        // TODO add your handling code here:
        new Staff().setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_staffActionPerformed

    private void AdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministratorActionPerformed
        // TODO add your handling code here:
        new AdministratorGUI().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_AdministratorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Administrator;
    private javax.swing.JButton Appointment;
    private javax.swing.JButton Logout;
    private javax.swing.JLabel MainMenu;
    private javax.swing.JButton PatientRegistration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton medistaff;
    private javax.swing.JButton staff;
    // End of variables declaration//GEN-END:variables
}
