/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

import java.io.BufferedReader;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;

public class MedicalstaffGUI extends javax.swing.JFrame {

    /**
     * Creates new form MedicalstaffGUI
     */
    public MedicalstaffGUI() {
        initComponents();
          setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doctor = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        tele = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        namee = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        specialization = new javax.swing.JLabel();
        S = new javax.swing.JTextField();
        consultationFee = new javax.swing.JLabel();
        licenseNumber = new javax.swing.JLabel();
        L = new javax.swing.JTextField();
        C = new javax.swing.JTextField();
        yearsOfExperience = new javax.swing.JLabel();
        Y = new javax.swing.JTextField();
        m = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doctor.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        doctor.setText("Doctor");
        getContentPane().add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 23, -1, -1));

        id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        id.setText("Doctor ID");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setText("Doctor Name");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        dob.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dob.setText("Date of Birth");
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        a.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        a.setText("Address");
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        tele.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tele.setText("Telephone number");
        getContentPane().add(tele, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 100, -1));
        getContentPane().add(namee, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 90, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 90, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, -1));
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, -1, -1));

        specialization.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        specialization.setText("Specialization");
        getContentPane().add(specialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, -1));

        consultationFee.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultationFee.setText("Consultation Fee");
        getContentPane().add(consultationFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        licenseNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        licenseNumber.setText("LicenseNumber");
        getContentPane().add(licenseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));
        getContentPane().add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 90, -1));
        getContentPane().add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 100, -1));

        yearsOfExperience.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        yearsOfExperience.setText("Years Of Experience");
        getContentPane().add(yearsOfExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        getContentPane().add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 100, -1));

        m.setText("Main Menu");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, 0, 930, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
      if (ID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Doctor ID");
        }
      else if (namee.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Doctor Name");
        } 
      else if (date.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Date of Birth");
        } 
      else if (address.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Address");
        } 
      else if (telephone.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Telephone Number");
        } 
      else if (S.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Specialization");
        } 
      else if (L.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter License Number");
        } 
      else if (C.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Consultation Fee");
        } 
      else if (Y.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Years of Experience");
        }  
     String targetID = ID.getText().trim();
    ArrayList<String> lines = new ArrayList<>();
    String fileName = "Doctors.txt";
    try {
        File file = new File(fileName);
        boolean fileExists = file.exists();

        // Read all existing lines
        if (fileExists) {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line;
            while ((line = reader.readLine()) != null) {
                // Keep header
                if (line.startsWith("DoctorID")) {
                    lines.add(line);
                    continue;
                }

                // Replace line if DoctorID matches
                if (line.trim().startsWith(targetID)) {
                    String format = "%-12s %-20s %-12s %-20s %-15s %-15s %-15s %-15s %-10s";
                    String updatedLine = String.format(format,
                            ID.getText(),
                            namee.getText(),
                            date.getText(),
                            address.getText(),
                            telephone.getText(),
                            S.getText(),
                            L.getText(),
                            C.getText(),
                            Y.getText()
                    );
                    lines.add(updatedLine);
                } else {
                    lines.add(line);
                }
            }
            reader.close();
        }

        // If file did not exist, add header
        if (!fileExists) {
            String header = String.format("%-12s %-20s %-12s %-20s %-15s %-15s %-15s %-15s %-10s",
                    "DoctorID", "Name", "DOB", "Address", "Telephone",
                    "Specialization", "LicenseNumber", "ConsultationFee", "YearsExp");
            lines.add(header);
        }

        // If DoctorID did not exist in file, add as new
        boolean exists = false;
        for (String l : lines) {
            if (l.trim().startsWith(targetID)) {
                exists = true;
                break;
            }
        }
        if (!exists) {
            String format = "%-12s %-20s %-12s %-20s %-15s %-15s %-15s %-15s %-10s";
            String newLine = String.format(format,
                    ID.getText(),
                    namee.getText(),
                    date.getText(),
                    address.getText(),
                    telephone.getText(),
                    S.getText(),
                    L.getText(),
                    C.getText(),
                    Y.getText()
            );
            lines.add(newLine);
        }

        // Write all lines back
        FileWriter writer = new FileWriter(fileName, false); // overwrite
        for (String l : lines) {
            writer.write(l + "\n");
        }
        writer.close();

        JOptionPane.showMessageDialog(this, "Doctor details saved/updated successfully!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "File error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }


        
      
    }//GEN-LAST:event_saveActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
    
          // TODO add your handling code here:
        new MainMenuGUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalstaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalstaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalstaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalstaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalstaffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField L;
    private javax.swing.JTextField S;
    private javax.swing.JTextField Y;
    private javax.swing.JLabel a;
    private javax.swing.JTextField address;
    private javax.swing.JLabel consultationFee;
    private javax.swing.JTextField date;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel doctor;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel licenseNumber;
    private javax.swing.JButton m;
    private javax.swing.JLabel name;
    private javax.swing.JTextField namee;
    private javax.swing.JButton save;
    private javax.swing.JLabel specialization;
    private javax.swing.JLabel tele;
    private javax.swing.JTextField telephone;
    private javax.swing.JLabel yearsOfExperience;
    // End of variables declaration//GEN-END:variables
}
