/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

import javax.swing.JOptionPane;

public class PatientRegistation extends javax.swing.JFrame {

    /**
     * Creates new form PatientRegistation
     */
    public PatientRegistation() {
        initComponents();
          setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null); // center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PersonID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PatientID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        DateOfBirth = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Gender = new javax.swing.JComboBox<>();
        ContactNumber = new javax.swing.JTextField();
        BloodGroup = new javax.swing.JTextField();
        Allergies = new javax.swing.JTextField();
        EmergencyContact = new javax.swing.JTextField();
        Insuranceinfo = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Registrationdate = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel1.setText("Patient Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Person ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, -1));

        PersonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonIDActionPerformed(evt);
            }
        });
        getContentPane().add(PersonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Patient ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 150, -1));

        PatientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientIDActionPerformed(evt);
            }
        });
        getContentPane().add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 150, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("First Name ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 150, -1));
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 100, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 150, -1));

        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 150, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Date Of Birth");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, -1));
        getContentPane().add(DateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 150, -1));

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 150, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 150, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Contact Number");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 150, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 150, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("Registration Date ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 150, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("Blood Group");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 150, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setText("Allergies");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("Emergency Contact");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("Insurance Info");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 150, -1));

        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Gender", "Male", "Femele" }));
        getContentPane().add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, -1));

        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });
        getContentPane().add(ContactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, -1));

        BloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupActionPerformed(evt);
            }
        });
        getContentPane().add(BloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 150, -1));

        Allergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllergiesActionPerformed(evt);
            }
        });
        getContentPane().add(Allergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 150, -1));

        EmergencyContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyContactActionPerformed(evt);
            }
        });
        getContentPane().add(EmergencyContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 150, -1));

        Insuranceinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceinfoActionPerformed(evt);
            }
        });
        getContentPane().add(Insuranceinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 150, -1));

        Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressActionPerformed(evt);
            }
        });
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, -1));

        Registrationdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrationdateActionPerformed(evt);
            }
        });
        getContentPane().add(Registrationdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, -1));

        Save.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        mainmenu.setText("MAIN MENU");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        getContentPane().add(mainmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/BG.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 680, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PatientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientIDActionPerformed

    private void RegistrationdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrationdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrationdateActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed

      if (PersonID.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER PERSON ID" ,"",WIDTH);
      }  
   
      else if (FirstName.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER FIRST NAME" ,"",WIDTH);
      }  
       else if (DateOfBirth.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER Date Of Birth" ,"",WIDTH);
      }  
       else if (Gender.getSelectedItem().equals("Select Your Gender")){
          JOptionPane.showMessageDialog(rootPane,"PLEASE SELECTE THE GENDER" ,"",WIDTH);
      }  
        else if (ContactNumber.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER CONTACT NUMBER " ,"",WIDTH);
      }  
         else if (Address.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER ADDRESS" ,"",WIDTH);
      } 
         else if (Registrationdate.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER DATE" ,"",WIDTH);
      }  
       else if (PatientID.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER PATIENT ID" ,"",WIDTH);
      }  
      else if (LastName.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER LAST NAME" ,"",WIDTH);
      }  
     
      else if (Email.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER EMAIL" ,"",WIDTH);
      }  
      else if (BloodGroup.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER YOUR BLOOD GROUP" ,"",WIDTH);
      }  
     
      else if (Allergies.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER YOUR ALLERGIES" ,"",WIDTH);
      }  
      
      else if (EmergencyContact.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER YOUR EMERGENCY CONTACT" ,"",WIDTH);
      }  
      
      else if (Insuranceinfo.getText().isEmpty()){
          JOptionPane.showMessageDialog(rootPane,"PLEASE ENETER INSURANCE INFROMATION" ,"",WIDTH);
      }  
      else{
          Patient obj=new Patient ();
          obj.setPersonID(PersonID.getText());
          obj.setFirstName(FirstName.getText());
          obj.setDateOfBirth(DateOfBirth.getText());
          obj.setGender((String)Gender.getSelectedItem());
          obj.setContactNumber(ContactNumber.getText());
          obj.setAddress(Address.getText());
          obj.setRegistrationDate(Registrationdate.getText());
          obj.setPatientID(PatientID.getText());
          obj.setLastName(LastName.getText());
          obj.setEmail(Email.getText());
          obj.setBloodGroup(BloodGroup.getText());
          obj.setAllergies(Allergies.getText());
          obj.setEmergencyContact(EmergencyContact.getText());
          obj.setInsuranceInfo(Insuranceinfo.getText());
          
         obj.registerPatient();
 
      }
    }//GEN-LAST:event_SaveActionPerformed

    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void EmergencyContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyContactActionPerformed

    private void AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        // TODO add your handling code here:
        new MainMenuGUI().setVisible(true);
this.dispose();

    }//GEN-LAST:event_mainmenuActionPerformed

    private void InsuranceinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsuranceinfoActionPerformed

    private void AllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllergiesActionPerformed

    private void BloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodGroupActionPerformed

    private void PersonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonIDActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRegistation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientRegistation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Allergies;
    private javax.swing.JTextField BloodGroup;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JTextField DateOfBirth;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField EmergencyContact;
    private javax.swing.JTextField FirstName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField Insuranceinfo;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField PatientID;
    private javax.swing.JTextField PersonID;
    private javax.swing.JTextField Registrationdate;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton mainmenu;
    // End of variables declaration//GEN-END:variables
}
