/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Registation;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bagya
 */
public class Staff extends javax.swing.JFrame {

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
         setSize(637, 430);
    setResizable(false);
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staff = new javax.swing.JLabel();
        staffID = new javax.swing.JLabel();
        department = new javax.swing.JLabel();
        hireDate = new javax.swing.JLabel();
        salary = new javax.swing.JLabel();
        workSchedule = new javax.swing.JLabel();
        staffType = new javax.swing.JLabel();
        qualifications1 = new javax.swing.JLabel();
        s = new javax.swing.JTextField();
        d = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        money = new javax.swing.JTextField();
        w = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        q = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        staff.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        staff.setText("Staff registation");
        getContentPane().add(staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 175, -1));

        staffID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staffID.setText("Staff ID");
        getContentPane().add(staffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, -1));

        department.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        department.setText("Department");
        getContentPane().add(department, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 146, -1, -1));

        hireDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hireDate.setText("Hire Date");
        getContentPane().add(hireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 205, -1, -1));

        salary.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salary.setText("Salary");
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 262, -1, -1));

        workSchedule.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        workSchedule.setText("Work Schedule");
        getContentPane().add(workSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        staffType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        staffType.setText("Staff Type");
        getContentPane().add(staffType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 73, -1));

        qualifications1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qualifications1.setText("Qualifications");
        getContentPane().add(qualifications1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, -1, -1));

        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 100, -1));
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 140, 100, -1));
        getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 202, 100, -1));
        getContentPane().add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 259, 100, -1));
        getContentPane().add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 100, -1));
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 100, -1));
        getContentPane().add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 100, -1));

        save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 100, 40));

        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setText("Main Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Registation/images/appoinment.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 630, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (s.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Staff ID");
        }
      else if (h.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Hire date");
        } 
      else if (money.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Salary");
        } 
      else if (q.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Qualifications");
        } 
      else if (t.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Staff type");
        } 
      else if (d.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Department");
        } 
      else if (w.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Work shcedule");
        } 
      
      else {
            // Create Doctor object and register
             Doctor doc = new Doctor();
        doc.setId(d.getText());
        doc.setName(h.getText());
        doc.setDob(money.getText());
        doc.setAddress(q.getText());
        doc.setTelephone(s.getText());
        doc.setSpecialization(t.getText());
        doc.setLicenseNumber(w.getText());


       
        
   {                                     
    // Check all fields
    if (s.getText().isEmpty() || h.getText().isEmpty() || money.getText().isEmpty() ||
        q.getText().isEmpty() || t.getText().isEmpty() || d.getText().isEmpty() ||
        w.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields");
        return;
    }

    String targetID = s.getText().trim();
    ArrayList<String> lines = new ArrayList<>();
    String fileName = "Staff.txt";

    try {
        File file = new File(fileName);
        boolean fileExists = file.exists();

        // Read existing file
        if (fileExists) {
            BufferedReader reader = new BufferedReader(new FileReader(file));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.startsWith("StaffID")) { // Keep header
                    lines.add(line);
                    continue;
                }

                String[] parts = line.trim().split("\\s+");
                if (parts[0].equals(targetID)) {
                    // Update existing staff
                    String format = "%-12s %-15s %-12s %-10s %-15s %-12s %-15s";
                    String updatedLine = String.format(format,
                        s.getText(), d.getText(), h.getText(), money.getText(),
                        w.getText(), t.getText(), q.getText()
                    );
                    lines.add(updatedLine);
                } else {
                    lines.add(line);
                }
            }
            reader.close();
        }

        // Add header if file did not exist
        if (!fileExists) {
            String header = String.format("%-12s %-15s %-12s %-10s %-15s %-12s %-15s",
                    "StaffID", "Department", "HireDate", "Salary",
                    "WorkSchedule", "StaffType", "Qualifications");
            lines.add(header);
        }

        // Add new staff if not exists
        boolean exists = false;
        for (String l : lines) {
            String[] parts = l.trim().split("\\s+");
            if (parts[0].equals(targetID)) {
                exists = true;
                break;
            }
        }
        if (!exists) {
            String format = "%-12s %-15s %-12s %-10s %-15s %-12s %-15s";
            String newLine = String.format(format,
                    s.getText(), d.getText(), h.getText(), money.getText(),
                    w.getText(), t.getText(), q.getText()
            );
            lines.add(newLine);
        }

        // Write all lines back
        FileWriter writer = new FileWriter(fileName, false);
        for (String l : lines) {
            writer.write(l + "\n");
        }
        writer.close();

        JOptionPane.showMessageDialog(this, "Staff details saved successfully!");

        // Clear fields
        s.setText(""); d.setText(""); h.setText(""); money.setText("");
        w.setText(""); t.setText(""); q.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "File error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    }
    }//GEN-LAST:event_saveActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        
        new MainMenuGUI().setVisible(true);
this.dispose();
    }//GEN-LAST:event_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JLabel department;
    private javax.swing.JTextField h;
    private javax.swing.JLabel hireDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton menu;
    private javax.swing.JTextField money;
    private javax.swing.JTextField q;
    private javax.swing.JLabel qualifications1;
    private javax.swing.JTextField s;
    private javax.swing.JLabel salary;
    private javax.swing.JButton save;
    private javax.swing.JLabel staff;
    private javax.swing.JLabel staffID;
    private javax.swing.JLabel staffType;
    private javax.swing.JTextField t;
    private javax.swing.JTextField w;
    private javax.swing.JLabel workSchedule;
    // End of variables declaration//GEN-END:variables
}
